name: quantum-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy<2
  - networkx>=2.6,<4
  - tqdm>=4.64,<5
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - psutil
  - python-igraph
  - pymetis
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - -f https://data.pyg.org/whl/torch-2.5.1%2Bcu121.html
      - torch==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - torchaudio==2.5.1+cu121
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt25cu121
      - torch-sparse==0.6.18+pt25cu121
      - torch-cluster==1.6.3+pt25cu121
      - torch-spline-conv==1.2.2+pt25cu121
      - pennylane==0.42.3
      - pennylane-lightning==0.42.0
      - pennylane-lightning-gpu==0.42.0
      - autoray==0.7.2
      - cvxpy==1.7.3
      - scs==3.2.8
      - cuquantum-python-cu12==25.3.0.post0